name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    name: Release
    if: contains(github.event.pull_request.labels.*.name, 'release') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build

      - name: Build
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

      - name: Get version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ github.event.pull_request.body }}
          tag_name: ${{ env.VERSION }}
          draft: false
          prerelease: false
